// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIXv3fLWIV9wP1MkLEL_CUzQLBu04ttwY',
    appId: '1:343832810991:web:4015133395c130d977521a',
    messagingSenderId: '343832810991',
    projectId: 'happyours-80c4c',
    authDomain: 'happyours-80c4c.firebaseapp.com',
    storageBucket: 'happyours-80c4c.appspot.com',
    measurementId: 'G-JFPL7RL4JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0B22hAeYgWGvB_7kGCHavsYdFaZfBPcI',
    appId: '1:343832810991:android:5020e26548e4458d77521a',
    messagingSenderId: '343832810991',
    projectId: 'happyours-80c4c',
    storageBucket: 'happyours-80c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1QAsPtogQv91IFIHFi-rc7eSKKW8U2RM',
    appId: '1:343832810991:ios:744845c98f2ea20a77521a',
    messagingSenderId: '343832810991',
    projectId: 'happyours-80c4c',
    storageBucket: 'happyours-80c4c.appspot.com',
    iosClientId: '343832810991-7oiodiqmb3ar22vsaio64spmm83gsh1n.apps.googleusercontent.com',
    iosBundleId: 'com.nyu.happyours',
  );
}
